### ISSUE TITLE
How is `SPLIT_ACTIVE=true yarn dev` supposed to work?

### ISSUE THREAD

**Issue by curiousercreative** [aiji42/next-with-split#115] opened 2021-11-23 21:39 UTC
Here are my observations of its current behavior:
- "original" branch host seems to be overridden in favor of the local dev server (http://localhost:3000) and all resources load
- when "challenger" is assigned (verify by checking cookie) all `/_next/static/` resources 404
- cookie assignment does appear to properly split on weighting

**Comment by aiji42** [comment] 2021-11-24 01:04
@curiousercreative, Thanks for the question.
If it works correctly, the A/B test distribution will work in the development environment if `SPLIT_ACTIVE=true` is given.

From the contents of your question, it seems that it is not running properly. Please provide the following information for me to investigate.
- next-with-split version
- Next.js version
- next.config.js

Regards.

**Comment by curiousercreative** [comment] 2021-11-24 20:34
What does "work in development environment" mean though? It could be any of the following:
1. dev server reverse-proxies all traffic (original and canary in my case) for all branches as specified
2. dev server only reverse-proxies the original branch and serves local app for all variation branches
3. dev server only reverse-proxies the variation branches (canary in my case) and servers local app for the original branch

next-with-split: `4.1.0`
next: `12.0.4`

next.config.js (abbreviated)
```javascript

const withSplit = require('next-with-split')({
  splits: {
    canary: {
      hosts: {
        original: {
          host: 'https://my.domain.tld',
        },
        canary: {
          host: 'https://canary.my.domain.tld',
        },
      },
    },
  },
});
module.exports = withSentryConfig(
  withSplit(withTM(moduleExports)),
  SentryWebpackPluginOptions
);
```

**Comment by aiji42** [comment] 2021-11-25 06:21
I understand what you are reporting.
The split behavior of `next-with-split` A/B tests is always consistent whether the execution environment is the development server or the production server. (You need to specify `SPLIT_ACTIVE` in the development environment because the splitting is disabled by default, but it makes no difference in the behavior.)
Responding with the three options you provided, No. 1 is correct in some cases, and No. 3 is correct in others.

This library defines `original`, `master`, and `main` as the original branches.
https://github.com/aiji42/next-with-split/blob/main/src/constants.ts

If you set the key of `hosts` to a string matching these, the distribution will be given `isOriginal: true`.
https://github.com/aiji42/next-with-split/blob/main/src/make-runtime-config.ts#L27

If a distribution with `isOriginal: false` is selected, it will be rewritten to the host of the specified domain, but if the distribution has `isOriginal: true`, it will not be rewritten and will be passed through to the same origin as the request (localhost for development servers).
https://github.com/aiji42/next-with-split/blob/main/src/middleware.ts#L11

With the configuration you provided in next.config.js, accesses assigned to `original` will automatically be directed to localhost, regardless of the domain you set. So No. 1 is the correct answer in this case. Also, if you set the hosts key to `canary1` and `canary2`, both of them will be `isOriginal: false`, so both of them will direct access to the domain you set, so No. 3 is the correct answer in this case.

**Comment by curiousercreative** [comment] 2021-11-25 15:20
@aiji42 thanks for that explanation. I seem to be reproducing all of that as described. Even so, there still appears to be something wrong as whenever my challenger branch is selected and specified as a remote (not `http://localhost:3000`) then all of those static resources 404.

**Comment by aiji42** [comment] 2021-11-25 15:29
@curiousercreative The Challenger branch also needs to install `next-with-split` and update `next.config.js`, have you completed those steps?
Please refer to Usage No. 1 and No. 2 in [READE](https://github.com/aiji42/next-with-split#usage)

**Comment by curiousercreative** [comment] 2021-11-30 20:25
@aiji42 here's some actual code and deploys that reproduce:
- [Original branch](https://github.com/curiousercreative/next-with-split-demo/tree/main) deployed as production to [https://next-with-split-demo.vercel.app/](https://next-with-split-demo.vercel.app/)
- [Challenger branch](https://github.com/curiousercreative/next-with-split-demo/tree/canary) deployed as preview to [https://next-with-split-demo-git-canary-curiousercreative.vercel.app/](https://next-with-split-demo-git-canary-curiousercreative.vercel.app/)

**Comment by aiji42** [comment] 2021-12-01 02:46
Thank you for presenting the sample code.
The problem is caused by the fact that the value of each host contains a trailing slash. I removed it and it worked fine.
And please specify the path (this is not relevant for this problem, but it is preferable).

```js
const withSplit = require('next-with-split')({
  splits: {
   canary: {
     path: '/', // Specify the target range of the A/B test. (Regular expressions are also acceptable.)
     hosts: {
       original: 'https://next-with-split-demo.vercel.app', // Remove the trailing slash.
       canary: 'https://next-with-split-demo-git-canary-curiousercreative.vercel.app', // Remove the trailing slash.
     },
   },
 },
});

module.exports = withSplit({
  reactStrictMode: true,
});

```

I would like to prevent these problems from occurring by updating the configuration values to be validated at server startup.

**Comment by aiji42** [comment] 2021-12-01 02:46
@curiousercreative 
Thank you for presenting the sample code.
The problem is caused by the fact that the value of each host contains a trailing slash. I removed it and it worked fine.
And please specify the path (this is not relevant for this problem, but it is preferable).

```js
const withSplit = require('next-with-split')({
  splits: {
   canary: {
     path: '/', // Specify the target range of the A/B test. (Regular expressions are also acceptable.)
     hosts: {
       original: 'https://next-with-split-demo.vercel.app', // Remove the trailing slash.
       canary: 'https://next-with-split-demo-git-canary-curiousercreative.vercel.app', // Remove the trailing slash.
     },
   },
 },
});

module.exports = withSplit({
  reactStrictMode: true,
});

```

I would like to prevent these problems from occurring by updating the configuration values to be validated at server startup.

**Comment by aiji42** [comment] 2021-12-08 15:01
Do you need any other support? If it's OK, I'll close this Issue.

**Closed** 2021-12-08 15:05 UTC

**Comment by curiousercreative** [comment] 2021-12-13 17:13
@aiji42 thanks for that feedback. I can confirm that the trailing slash was a problem (and your updated validation does err on server startup!) and the [repro steps here work properly in production and dev](https://github.com/aiji42/next-with-split/issues/115#issuecomment-982991902).

**Comment by curiousercreative** [comment] 2021-12-13 17:18
FWIW, it may be helpful for others to see a bare bones repo (with active deploys) of this most basic traffic split. The README is good, but it's expressing a lot more than the boilerplate necessary to build upon.
